version: '3.3'

# NB: Add to /etc/host 127.0.0.1 kafka in order to use this on local development
services:
  #ZOOKEEPER
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '32181:32181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"
  #BROKER 1
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    ports:
      - '9092:9092'
      - '29092:29092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "moby:127.0.0.1"
  kafka-manager:
    depends_on:
      - kafka
      - zookeeper
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:32181
      APPLICATION_SECRET: letmein
    links:
      - zookeeper
  #SCHEMA-REGISTRY
  schema_registry:
    image: confluentinc/cp-schema-registry
    hostname: schema_registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:32181'
      ACCESS_CONTROL_ALLOW_METHOS:  'GET,POST,PUT,OPTIONS'
      ACCESS_CONTROL_ALLOW_ORIGIN: '*'
    extra_hosts:
      - "moby:127.0.0.1"
  
  #KAFKA-REST-PROXY
  kafka-rest:
    image: confluentinc/cp-kafka-rest
    hostname: kafka-rest
    ports:
      - "8082:8082"
    environment: 
      ZK_CONNECTION_STRING: 'zookeeper:32181'
      KAFKA_REST_ZOOKEEPER_CONNECT: 'zookeeper:32181'
      KAFKA_REST_BOOTSTRAP_SERVERS: 'kafka:29092'
      KAFKA_REST_HOST_NAME: 'kafka'
    depends_on: 
      - zookeeper
      - kafka
      - schema_registry
  #TOPICS UI
  kafka-topic-ui:
    image: landoop/kafka-topics-ui
    ports: 
      - "8000:8000"
    environment:
      KAFKA_REST_PROXY_URL: kafka-rest:8082
      PROXY: 'true'
    depends_on: 
      - kafka-rest
  #Schema registry ui
  schema-registry-ui:
    image: landoop/schema-registry-ui
    ports:
      - "8083:8083"
    environment: 
      SCHEMAREGISTRY_URL: schema_registry:8081
      PORT: 8083
      PROXY: 'true'
    depends_on: 
      - schema_registry
  cassandra:
    image: cassandra:3.0
    ports:
      - "9042:9042"
